### ISSUE TITLE
model_name_or_path加载本地模型出错,怎么才能加载本地已经下载好的模型

### ISSUE THREAD

**Issue by xldistance** [shuxueslpi/chatGLM-6B-QLoRA#10]
修改如下parser.add_argument('--model_name_or_path', type=str, default='H:/langchain/ChatGLM-6B-Model', help='模型id或local path')，运行出错
![QQ截图20230630133704](https://github.com/shuxueslpi/chatGLM-6B-QLoRA/assets/29418474/91ea8724-6850-4e13-9b40-592bf3634ea7)

**Comment by shuxueslpi** [comment]
@xldistance windows好像得这么写：
H:\\langchain\\ChatGLM-6B-Model
