### ISSUE TITLE
带instruction和input的数据集怎么微调啊？

### ISSUE THREAD

**Issue by weifan-zhao** [shuxueslpi/chatGLM-6B-QLoRA#16]

**Comment by shuxueslpi** [comment]
@weifan-zhao 代码里把这两个key对应的内容合并的，有其他想法也可以直接改这部分代码：
train_qlora.py的61~64行

question = global_args.prompt_text + example['instruction']
if example.get('input', None):
    if example['input'].strip():
        question += f'''\n{example['input']}'''
answer = example['output']
