### ISSUE TITLE
两张卡训练，16*2，OOM

### ISSUE THREAD

**Issue by cheney369** [shuxueslpi/chatGLM-6B-QLoRA#20]
模型加载时内存使用大概12G，代码运行到model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=True)这行突然变成24G左右，然后就报错了。还没有开始训练。fp16，batch_size设成1。

**Comment by shuxueslpi** [comment]
多卡目前还有问题，一张卡12G显存可以跑下整个实验



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月10日 15:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [shuxueslpi/chatGLM-6B-QLoRA] 两张卡训练，16*2，OOM (Issue #20) |

模型加载时内存使用大概12G，代码运行到model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=True)这行突然变成24G左右，然后就报错了。还没有开始训练。fp16，batch_size设成1。

**Comment by cheney369** [comment]
那我如果只指定一张卡去训练，是可以跑下实验的是吗？有试了以下方法，也是不行。
import os 
os.environ("CUDA_VISIBLE_DEVICE") = "0"
或
在加载model操作后，model.to(cuda:0)

**Comment by shuxueslpi** [comment]
那个环境变量好像是CUDA_VISIBLE_DEVICES



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月10日 16:16 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [shuxueslpi/chatGLM-6B-QLoRA] 两张卡训练，16*2，OOM (Issue #20) |

那我如果只指定一张卡去训练，是可以跑下实验的是吗？有试了以下方法，也是不行。
import os
os.environ("CUDA_VISIBLE_DEVICE") = "0"
或
在加载model操作后，model.to(cuda:0)

**Comment by cheney369** [comment]
> 那个环境变量好像是CUDA_VISIBLE_DEVICES
> […](#)

是的打错了,不好意思。不过指定单张16G的卡训练时，也会报OOM错误。
![Xnip2023-07-11_09-24-06](https://github.com/shuxueslpi/chatGLM-6B-QLoRA/assets/50095589/cde41f13-5102-46ea-ab9c-a081ab55ba01)

**Comment by shuxueslpi** [comment]
@cheney369 chatGLM2是在load模型阶段就OOM了吗？还是训练阶段？
还有你的16G的卡，是V100吗？

**Comment by shuxueslpi** [comment]
@cheney369 https://github.com/shuxueslpi/chatGLM-6B-QLoRA/issues/14
看这个，和你一样的报错，可能是transformers的版本问题

**Comment by cheney369** [comment]
> @cheney369 #14
> 看这个，和你一样的报错，可能是transformers的版本问题

确实是transformers的版本问题，现在显存这部分没问题了。但是出现一个新的问题，就是在这一句中会报错：
question_length = input_ids.index(tokenizer.bos_token_id)
查了一下原因是因为chatglm2中没有bos_token_id，而chatglm1是有的，所以在训练2的时候这行需要进行替换。

**Comment by shuxueslpi** [comment]
@cheney369 你用的貌似不是我最新的代码，这部分应该是改过了的

**Comment by cheney369** [comment]
> @cheney369 你用的貌似不是我最新的代码，这部分应该是改过了的

确实是，实在抱歉。

**Comment by 2512309z** [comment]
> > @cheney369 #14
> > 看这个，和你一样的报错，可能是transformers的版本问题
> 
> 确实是transformers的版本问题，现在显存这部分没问题了。但是出现一个新的问题，就是在这一句中会报错： question_length = input_ids.index(tokenizer.bos_token_id) 查了一下原因是因为chatglm2中没有bos_token_id，而chatglm1是有的，所以在训练2的时候这行需要进行替换。

请问你最后用的是哪个版本的transformer？我也是OOM，没办法只有把batchsize改成1才能跑起来

**Comment by cheney369** [comment]
> > > @cheney369 #14
> > > 看这个，和你一样的报错，可能是transformers的版本问题
> > 
> > 
> > 确实是transformers的版本问题，现在显存这部分没问题了。但是出现一个新的问题，就是在这一句中会报错： question_length = input_ids.index(tokenizer.bos_token_id) 查了一下原因是因为chatglm2中没有bos_token_id，而chatglm1是有的，所以在训练2的时候这行需要进行替换。
> 
> 请问你最后用的是哪个版本的transformer？我也是OOM，没办法只有把batchsize改成1才能跑起来

transformers == 4.30.2.       batch_size=4的时候单卡显存占用7G.

**Comment by 2512309z** [comment]
> > > > @cheney369 #14
> > > > 看这个，和你一样的报错，可能是transformers的版本问题
> > > 
> > > 
> > > 确实是transformers的版本问题，现在显存这部分没问题了。但是出现一个新的问题，就是在这一句中会报错： question_length = input_ids.index(tokenizer.bos_token_id) 查了一下原因是因为chatglm2中没有bos_token_id，而chatglm1是有的，所以在训练2的时候这行需要进行替换。
> > 
> > 
> > 请问你最后用的是哪个版本的transformer？我也是OOM，没办法只有把batchsize改成1才能跑起来
> 
> transformers == 4.30.2. batch_size=4的时候单卡显存占用7G.

我的版本没问题，我可能是自己编辑的单条训练数据集字符过长了，数据集太难编辑了，不知道什么样的数据集才算是好的数据集，哎。。。。
