### ISSUE TITLE
不能训练被加载的8bit模型

### ISSUE THREAD

**Issue by HBdingdang** [shuxueslpi/chatGLM-6B-QLoRA#30]
微调chatGLM2与chatGLM1时，加载出现同样的错误
![微信图片_20230803194410](https://github.com/shuxueslpi/chatGLM-6B-QLoRA/assets/130053388/929dfa50-1faf-4e79-80ac-f938f1147eba)

**Comment by shuxueslpi** [comment]
你是多卡的环境吗？目前这个代码只是单卡的，如果是多卡，可以在运行前加：
CUDA_VISIBLE_DEVICES='0' python3 train_qlora.py
最近比较忙，还没时间搞多卡的模式。

**Comment by HBdingdang** [comment]
好的，改完可以跑了，非常感谢
