### ISSUE TITLE
数据集格式instruction,input,output时tokenized出错

### ISSUE THREAD

**Issue by HBdingdang** [shuxueslpi/chatGLM-6B-QLoRA#31]
我的数据格式{ "instruction": "相关信息", "input": "相关提问", "output": "相关回答" }
数据集格式不能这样嘛，我看那个train_qlora.py里可以处理这种格式呀
下面是报错信息
![微信图片_20230807104714](https://github.com/shuxueslpi/chatGLM-6B-QLoRA/assets/130053388/000551fa-aef5-48c0-9433-64ce9e11145b)

**Comment by shuxueslpi** [comment]
@HBdingdang 这里不是报的数据问题，是配置文件的问题，你看看你的chatGLM_6B_QLoRA.json这个文件是不是不是标准的json格式

**Comment by HBdingdang** [comment]
噢噢，知道了，我在jsonl文件中注释了，去掉就好了，jsonl不能有注释是把
