### ISSUE TITLE
训练结束后没有保存完整的adapter文件

### ISSUE THREAD

**Issue by daihuaiii** [shuxueslpi/chatGLM-6B-QLoRA#41]
训练结束后saved_files文件夹中只有adapter_config.json,adapter_model.bin,README.md三个文件。

**Comment by daydayup-zyn** [comment]
同样问题

**Comment by daihuaiii** [comment]
> 同样问题

将训练参数文件中的save_strategy修改为epoch或将save_steps修改小一点就可以保存。我使用的自己的数据集训练，数据量太小，没有到checkpoint的触发。

**Comment by daihuaiii** [comment]
> 同样问题

将训练参数文件中的save_strategy修改为epoch或将save_steps修改小一点就可以保存。我使用的自己的数据集训练，数据量太小，没有到checkpoint的触发。
