### ISSUE TITLE
模型训练执行问题

### ISSUE THREAD

**Issue by steamfeifei** [shuxueslpi/chatGLM-6B-QLoRA#9]
这是什么呀，怎么选择呢？
![image](https://github.com/shuxueslpi/chatGLM-6B-QLoRA/assets/44861931/b65cee3d-0722-4e4b-afcd-43f17f745620)

**Comment by steamfeifei** [comment]
已解决：
在训练文件开头配置环境变量：
`os.environ["WANDB_DISABLED"] = "true"`

**Comment by steamfeifei** [comment]
解决RuntimeError: Expected all tensors to be on the same device, but found at least two devices
主要是因为配置了多个gpu，代码中数据一会在cpu，一会在gpu运行，最好是放到同一个device中执行即可。
所以解决方案是，只使用一个gpu即可解决：
`
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"`

**Comment by Mou-Mou-L** [comment]
> 解决RuntimeError: Expected all tensors to be on the same device, but found at least two devices 主要是因为配置了多个gpu，代码中数据一会在cpu，一会在gpu运行，最好是放到同一个device中执行即可。 所以解决方案是，只使用一个gpu即可解决： ` import os os.environ["CUDA_VISIBLE_DEVICES"] = "0"`
> 
> refer [@Aicharm](https://blog.csdn.net/muye_IT/article/details/124956145)

大佬也是在docker环境运行的么？我没docker环境  能不能通过其他方式运行

**Comment by steamfeifei** [comment]
>我也没用docker环境呀，直接在linux后台跑的呢

**Comment by Mou-Mou-L** [comment]
我的是windows系统  之前用ptuning 微调 我就是用git bash 运行的脚本  可以微调 现在不行了

**Comment by steamfeifei** [comment]
> 我的是windows系统 之前用ptuning 微调 我就是用git bash 运行的脚本 可以微调 现在不行了

是报了什么错呀

**Comment by steamfeifei** [comment]
已经跑了一天了，看看效果如何：
![image](https://github.com/shuxueslpi/chatGLM-6B-QLoRA/assets/44861931/c465ac82-1eeb-4017-aa3a-81f1a20171dc)

**Comment by shuxueslpi** [comment]
@Mou-Mou-L windows可以安装linux子系统的，然后再安装docker desktop，就可以丝滑的用docker了，可以参考docker desktop的安装文档来

**Comment by Mou-Mou-L** [comment]
公司的电脑 装不了 打开系统虚拟机  系统就崩了  之前试过  哈哈

**Comment by Mou-Mou-L** [comment]
> > 我的是windows系统 之前用ptuning 微调 我就是用git bash 运行的脚本 可以微调 现在不行了
> 
> 是报了什么错呀

https://github.com/shuxueslpi/chatGLM-6B-QLoRA/issues/12#issuecomment-1614418173这个报错 大佬

**Comment by Mou-Mou-L** [comment]
> @Mou-Mou-L windows可以安装linux子系统的，然后再安装docker desktop，就可以丝滑的用docker了，可以参考docker desktop的安装文档来

公司的电脑 装不了 打开系统虚拟机 系统就崩了 之前试过 哈哈

**Comment by 2512309z** [comment]
> Solved: Configure environment variables at the beginning of the training file: `os.environ["WANDB_DISABLED"] = "true"`
已解决：
在训练文件开头配置环境变量：
os.environ["WANDB_DISABLED"] = "true"


请问一下 你说的  训练文件  是指的哪个文件？

**Comment by steamfeifei** [comment]
> > Solved: Configure environment variables at the beginning of the training file: `os.environ["WANDB_DISABLED"] = "true"`
> > 已解决：
> > 在训练文件开头配置环境变量：
> > os.environ["WANDB_DISABLED"] = "true"
> 
> 请问一下 你说的 训练文件 是指的哪个文件？

train_qlora.py 啊

**Comment by 2512309z** [comment]
> > > Solved: Configure environment variables at the beginning of the training file: `os.environ["WANDB_DISABLED"] = "true"`
> > > 已解决：
> > > 在训练文件开头配置环境变量：
> > > os.environ["WANDB_DISABLED"] = "true"
> > 
> > 
> > 请问一下 你说的 训练文件 是指的哪个文件？
> 
> train_qlora.py 啊

非常感谢 ！  搞定了！  也看到你另外一个回答。多显卡的报错的异常，也搞定了！
